server:
  port: 8600
spring:
  application:
    name: USER-DETAIL
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/koi
    password: Ga.4567.
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

userDetail:
  defaultStar: 2.5




