server:
  port: 8003
spring:
  application:
    name: ADMIN-SERVER
    cloud:
      kubernetes:
        reload:
          enabled: true
  security:
    user:
      name: grkem
      password: 1234
eureka:
  defaultUserName: grkem
  defaultPassword: 1234
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http:/{eureka.defaultUserName}:{eureka.defaultPassword}@localhost:8001/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
logging:
  config: http://localhost:8000/native/native/main/LogConfiguration/AdminServerLogback.xml
