server:
  port: 8003
spring:
  application:
    name: ADMIN-SERVER
    cloud:
      kubernetes:
        reload:
          enabled: true
  security:
    user:
      name: grkem
      password: 1234
eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://{eurekaUserName}:{eurakaPassword}@{eurakaURL}
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
logging:
  config: http://localhost:8000/native/native/main/LogConfiguration/AdminServerLogback.xml
  
  eurekaUserName: grkem
  eurakaPassword: 1234
  eurakaURL: localhost:8001/eureka/
