adminServerUsername: grkem
adminServerPassword: 1234
logbackURL: http://localhost:8000/native/native/main/LogConfiguration/AdminServerLogback.xml
eurakaUsername: grkem
eurakaPassword: 1234
eurakaIP: localhost:8001/eureka/


server:
  port: 8003
spring:
  application:
    name: ADMIN-SERVER
    cloud:
      kubernetes:
        reload:
          enabled: true
      inetutils:
        ignoredInterfaces:
          - docker0
          - veth.*
          - lo
          - lo*
          - eth0*
  security:
    user:
      name: ${adminServerUsername}
      password: ${adminServerPassword}
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eurakaUsername}:${eurakaPassword}@${eurakaIP}
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    hostname: asd
logging:
  config: ${logbackURL}
