server:
  port: 8003
spring:
  application:
    name: ADMIN-SERVER
    cloud:
      kubernetes:
        reload:
          enabled: true
  security:
    user:
      name: grkem
      password: 1234
eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eurakaUser}:${eurakaPassword}@${eurakaIP}
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
logging:
  config: ${logbackURL}
  
logbackURL: http://localhost:8000/native/native/main/LogConfiguration/AdminServerLogback.xml
eurakaUser: grkem
eurakaPassword: 1234
eurakaIP: localhost:8001/eureka/
