server:
  port: 8003
spring:
  application:
    name: ADMIN-SERVER
    cloud:
      kubernetes:
        reload:
          enabled: true
  security:
    user:
      name: grkem
      password: 1234
eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://grkem:1234@localhost:8001/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
