dataBaseURL: jdbc:postgresql://localhost:5432/koi
dataBaseUsername: postgres
dataBasePassword: Ga.4567.
logbackURL: http://localhost:8000/native/native/main/LogConfiguration/AuthServerLogback.xml
eurakaUsername: grkem
eurakaPassword: 1234
eurakaIP: localhost:8001/eureka/
resetPasswordTokenExpriationMinute: 2


server:
  port: 8004
spring:
  application:
    name: AUTH-SERVER
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: grkemaykackoi@gmail.com
    password: jpuahdpcwlzxylju
    port: '587'
  datasource:
    username: ${dataBaseUsername}
    url: ${dataBaseURL}
    password: ${dataBasePassword}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eurakaUsername}:${eurakaPassword}@${eurakaIP}
    healthcheck:
      enabled: true
logging:
  config: ${logbackURL}
