server:
  port: 8005
spring:
  application:
    name: AUTH-FILTER
  datasource:
    username: ${dataBaseUsername}
    url: ${dataBaseURL}
    password: ${dataBasePassword}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
      
dataBaseURL: jdbc:postgresql://localhost:5432/koi
dataBaseUsername: postgres
dataBasePassword: Ga.4567.
