dataBaseURL: jdbc:postgresql://localhost:543/koi
dataBaseUsername: postgres
dataBasePassword: Ga.4567.


server:
  port: 8005
spring:
  application:
    name: AUTH-FILTER
  datasource:
    username: ${dataBaseUsername}
    url: ${dataBaseURL}
    password: ${dataBasePassword}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
