dataBaseURL: jdbc:postgresql://192.168.1.109:5432/koi
dataBaseUsername: postgres
dataBasePassword: Ga.4567.
logbackURL: http://192.168.1.109:8000/native/native/main/LogConfiguration/AuthServerLogback.xml
eurakaUsername: grkem
eurakaPassword: 1234
eurakaIP: 192.168.1.109:8001/eureka/


server:
  port: 8004
spring:
  application:
    name: AUTH-SERVER
  datasource:
    username: ${dataBaseUsername}
    url: ${dataBaseURL}
    password: ${dataBasePassword}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eurakaUsername}:${eurakaPassword}@${eurakaIP}
    healthcheck:
      enabled: true
logging:
  config: ${logbackURL}
