server:
  port: 8602

spring:
  application:
    name: COMMENT-SERVICE
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/koi
    password: Ga.4567.
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

eureka:
  client:
    serviceUrl:
      defaultZone: http://grkem:1234@localhost:8001/eureka/
    healthcheck:
      enabled: true
logging:
  config: http://localhost:8000/native/native/main/LogConfiguration/CommentServiceLogback.xml   


