logbackURL: http://192.168.1.109:8000/native/native/main/LogConfiguration/EurakaServerLogback.xml
zipkinServerURL: http://192.168.1.109:9411


server:
  port: 8001
spring:
  application:
    name: EUREKA-SERVER
  security:
    user:
      name: grkem
      password: 1234
  zipkin:
    base-url: ${zipkinServerURL}
eureka:
  renewalPercentThreshold: 0.85
  instance:
    hostname: 192.168.1.109
encrypt:
  key: koiappconfigsecretkey
logging:
  config: ${logbackURL}
