logbackURL: http://localhost:8000/native/native/main/LogConfiguration/EurakaServerLogback.xml
zipkinServerURL: http://localhost:9411


server:
  port: 8001
spring:
  application:
    name: EUREKA-SERVER
  security:
    user:
      name: grkem
      password: 1234
  zipkin:
    base-url: ${zipkinServerURL}
eureka:
  instance:
    hostname: localhost
  server:
    getWaitTimeInMsWhenSyncEmpty: 2
  client:
    registerWithEureka: false
    fetchRegistry: false
encrypt:
  key: koiappconfigsecretkey
logging:
  config: ${logbackURL}

