spring:
  application:
    name: EUREKA-SERVER
  security:
    user:
      name: grkem
      password: 1234
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8001
eureka:
  instance:
    hostname: localhost 
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://grkem:1234@localhost:8001/eureka/
encrypt:
  key: koiappconfigsecretkey
