logbackURL: http://localhost:8000/native/native/main/LogConfiguration/GatewayServerLogback.xml
eurakaUsername: grkem
eurakaPassword: 1234
eurakaIP: localhost:8001/eureka/


server:
  port: 8002
spring:
  main:
    web-application-type: reactive
  application:
    name: GATEWAY-SERVER
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 5000
      routes:
        - id: authServer
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/auth/**
          metadata:
            response-timeout: 10000
            connect-timeout: 2000
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: fallbackAuth
                fallbackUri: forward:/fallbackAuthServer
        - id: userDetailService
          uri: lb://USER-DETAIL
          predicates:
            - Path=/userDetail/**
          metadata:
            response-timeout: 10000
            connect-timeout: 2000
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: fallbackUser
                fallbackUri: forward:/fallbackUserDetailService
        - id: eventService
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/event/**
          metadata:
            response-timeout: 10000
            connect-timeout: 2000
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: fallbackEvent
                fallbackUri: forward:/fallbackEventService
        - id: commentService
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/comment/**
          metadata:
            response-timeout: 10000
            connect-timeout: 2000
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: fallbackComment
                fallbackUri: forward:/fallbackCommentService
        - id: participantService
          uri: lb://PARTICIPANT-SERVICE
          predicates:
            - Path=/participant/**
          metadata:
            response-timeout: 10000
            connect-timeout: 20000
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: fallbackParticipant
                fallbackUri: forward:/fallbackParticipantService
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eurakaUsername}:${eurakaPassword}@${eurakaIP}
    healthcheck:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  config: ${logbackURL}
