dataBaseURL: jdbc:postgresql://localhost:5432/koi
dataBaseUsername: postgres
dataBasePassword: Ga.4567.
logbackURL: http://localhost:8000/native/native/main/LogConfiguration/ParticipantServiceLogback.xml
eurakaUsername: grkem
eurakaPassword: 1234
eurakaIP: localhost:8001/eureka/


server:
  port: 8603
spring:
  application:
    name: PARTICIPANT-SERVICE
  datasource:
    username: ${dataBaseUsername}
    url: ${dataBaseURL}
    password: ${dataBasePassword}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eurakaUsername}:${eurakaPassword}@${eurakaIP}
    healthcheck:
      enabled: true
logging:
  config: ${ParticipantServiceLogback.xml}
participantService:
  lastRejectDateline: 5
